package gui;

import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
*
* @author Björn Hedström
*/
public class MainMenu extends javax.swing.JPanel {

   /**
    * Creates new form MainMeny
    */
   public MainMenu() {
       initComponents();
       repaint();
   }
   
   public void paintComponent(Graphics g) {
		BufferedImage image = null;
		try {
			image = ImageIO.read(new File("C:\\Users\\edge\\Downloads\\speaker.png"));
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		   g.drawImage(image, 0, 0, null);
   }
   
   //Here begins the autogenerated code

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
   private void initComponents() {

       logo = new javax.swing.JLabel();
       jButton1 = new javax.swing.JButton();
       optionsButton = new javax.swing.JButton();
       exitButton = new javax.swing.JButton();

       setBackground(new java.awt.Color(255, 255, 255));
       setMaximumSize(new java.awt.Dimension(915, 600));
       setMinimumSize(new java.awt.Dimension(915, 600));

       logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("beat3.PNG"))); // NOI18N

       jButton1.setBackground(new java.awt.Color(204, 204, 204));
       jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("playSong.png"))); // NOI18N
       jButton1.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               jButton1ActionPerformed(evt);
           }
       });

       optionsButton.setBackground(new java.awt.Color(204, 204, 204));
       optionsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("options.png"))); // NOI18N

       exitButton.setBackground(new java.awt.Color(204, 204, 204));
       exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("exit.png"))); // NOI18N
       exitButton.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               exitButtonActionPerformed(evt);
           }
       });

       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
       this.setLayout(layout);
       layout.setHorizontalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
               .addContainerGap(329, Short.MAX_VALUE)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                   .addComponent(exitButton)
                   .addComponent(optionsButton)
                   .addComponent(jButton1)
                   .addComponent(logo))
               .addGap(329, 329, 329))
       );
       layout.setVerticalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addGap(35, 35, 35)
               .addComponent(logo)
               .addGap(93, 93, 93)
               .addComponent(jButton1)
               .addGap(18, 18, 18)
               .addComponent(optionsButton)
               .addGap(18, 18, 18)
               .addComponent(exitButton)
               .addContainerGap(72, Short.MAX_VALUE))
       );
   }// </editor-fold>                        

   private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
       // TODO add your handling code here:
   }                                        

   private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
	   System.exit(0);
   }                                          


   // Variables declaration - do not modify                     
   private javax.swing.JButton exitButton;
   private javax.swing.JButton jButton1;
   private javax.swing.JLabel logo;
   private javax.swing.JButton optionsButton;
   // End of variables declaration                   
}