package gui;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.beans.PropertyChangeSupport;
import java.io.File;
import java.io.IOException;
import java.net.URL;

import javax.imageio.ImageIO;

import services.HomogeneousFileHandler;
import services.IFileHandler;

/**
 *
 * @author Björn Hedström
 */
public class Options extends ZoomablePanel implements ActionListener{

	/**
	 * Creates new form Options
	 */
	public Options() {
		pcs = new PropertyChangeSupport(this);
		initComponents();
		repaint();
	}

	public void paintComponent(Graphics g) {
		super.paintComponent(g);
	}

	private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {                                           
		((CardPanel)this.getParent()).back();
	}


	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	private void initComponents() {

		titleLabel = new javax.swing.JLabel();
		disableBackground = new java.awt.Checkbox();
		volumeSlider = new javax.swing.JSlider();
		maxVolume = new javax.swing.JLabel();
		miniVolume = new javax.swing.JLabel();
		backButton = new javax.swing.JButton();
		volumeLabel = new javax.swing.JLabel();

		setBackground(new java.awt.Color(255, 255, 255));
		setMaximumSize(new java.awt.Dimension(914, 600));
		setMinimumSize(new java.awt.Dimension(914, 600));

		titleLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\edge\\Downloads\\options2.png")); // NOI18N

		disableBackground.setLabel("Disable background");

		volumeSlider.setBackground(new java.awt.Color(255, 255, 255));
		volumeSlider.setForeground(new java.awt.Color(255, 51, 102));
		volumeSlider.setMinorTickSpacing(10);
		volumeSlider.setPaintTicks(true);
		volumeSlider.setSnapToTicks(true);
		volumeSlider.setOpaque(false);

		maxVolume.setText("100");
		maxVolume.setForeground(Color.WHITE);

		miniVolume.setText("0");
		miniVolume.setForeground(Color.WHITE);

		backButton.setBackground(new java.awt.Color(204, 204, 204));
		backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("images\\back.png"))); // NOI18N
		backButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				backButtonActionPerformed(evt);
			}
		});

		volumeLabel.setText("Volume");
		volumeLabel.setForeground(Color.WHITE);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(layout.createSequentialGroup()
										.addGap(286, 286, 286)
										.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
												.addGroup(layout.createSequentialGroup()
														.addComponent(miniVolume)
														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addComponent(volumeLabel)
														.addGap(137, 137, 137)
														.addComponent(maxVolume))
														.addComponent(titleLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
														.addComponent(volumeSlider, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
														.addGroup(layout.createSequentialGroup()
																.addGap(385, 385, 385)
																.addComponent(disableBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
																.addGroup(layout.createSequentialGroup()
																		.addGap(329, 329, 329)
																		.addComponent(backButton)))
																		.addGap(286, 286, 286))

				);
		disableBackground.setBackground(Color.BLACK);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addGap(60, 60, 60)
						.addComponent(titleLabel)
						.addGap(106, 106, 106)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(maxVolume)
								.addComponent(miniVolume)
								.addComponent(volumeLabel))
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(volumeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(56, 56, 56)
								.addComponent(disableBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(76, 76, 76)
								.addComponent(backButton)
								.addContainerGap(95, Short.MAX_VALUE))
				);
	}// </editor-fold>                        



	// Variables declaration - do not modify                     
	private java.awt.Checkbox disableBackground;
	private javax.swing.JButton backButton;
	private javax.swing.JLabel maxVolume;
	private javax.swing.JLabel miniVolume;
	private javax.swing.JLabel titleLabel;
	private javax.swing.JLabel volumeLabel;
	private javax.swing.JSlider volumeSlider;
	private PropertyChangeSupport pcs;
	// End of variables declaration                   


	public void actionPerformed(ActionEvent e) {
		
		if(e.getSource().equals(volumeSlider)){
			pcs.firePropertyChange("volumeChange", null, volumeSlider.getValue());
		}

		if(e.getSource().equals(disableBackground)){
			pcs.firePropertyChange("backgroundSlider", true, disableBackground.getState());
		}

	}
}
