package gui;

import java.beans.PropertyChangeSupport;

/**
 *
 * @author Björn Hedström
 */
public class PauseMenuPanel extends javax.swing.JPanel {
	
	PropertyChangeSupport pcs;
	/**
	 * Creates new form PauseMenuPanel
	 */
	public PauseMenuPanel() {
		initComponents();
		pcs = new PropertyChangeSupport(this);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	private void initComponents() {

		quitButton = new javax.swing.JButton();
		resumeGameButton = new javax.swing.JButton();
		pauseLabel = new javax.swing.JLabel();

		setBackground(new java.awt.Color(255, 255, 255));
		setMaximumSize(new java.awt.Dimension(306, 370));
		setMinimumSize(new java.awt.Dimension(306, 370));

		resumeGameButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("images\\resume.png"))); // NOI18N
		resumeGameButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				resumeButtonActionPerformed(evt);
			}
		});

		quitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("images\\quitsong.png"))); // NOI18N
		quitButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				quitButtonActionPerformed(evt);
			}
		});

		pauseLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("images\\saveicon.png"))); // NOI18N

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addGap(25, 25, 25)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(quitButton)
								.addComponent(resumeGameButton)
								.addComponent(pauseLabel))
								.addGap(0, 23, Short.MAX_VALUE))
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
						.addGap(33, 33, 33)
						.addComponent(pauseLabel)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
						.addComponent(resumeGameButton)
						.addGap(18, 18, 18)
						.addComponent(quitButton)
						.addGap(22, 22, 22))
				);
	}

	private void resumeButtonActionPerformed(java.awt.event.ActionEvent evt) {
		pcs.firePropertyChange("resumeGame", true, false);
	}                                            

	private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {
		pcs.firePropertyChange("quitGame", true, false);
	}                                          


	// Variables declaration - do not modify                     
	private javax.swing.JLabel pauseLabel;
	private javax.swing.JButton resumeGameButton;
	private javax.swing.JButton quitButton;
	// End of variables declaration                   
}
