package gui;

import java.awt.Color;
import java.beans.PropertyChangeSupport;

import javax.swing.JTextField;

/**
 *
 * @author Björn Hedström
 */
@SuppressWarnings("serial")
public class ScorePanel extends ZoomablePanel {

	public ScorePanel() {
		pcs = new PropertyChangeSupport(this);
		initComponents();
	}

	public javax.swing.JLabel getArtistLabel() {
		return artistLabel;
	}

	public javax.swing.JLabel getCongratsLabel() {
		return congratsLabel;
	}

	public javax.swing.JLabel getScoreLabel() {
		return scoreLabel;
	}

	public javax.swing.JLabel getSongLabel() {
		return songLabel;
	}

	public javax.swing.JLabel getTitleLabel() {
		return titleLabel;
	}

	public JTextField[] getNameField() {
		return nameField;
	}

	public JTextField[] getScoreField() {
		return scoreField;
	}

	private void proccedButtonActionPerformed(java.awt.event.ActionEvent evt) { 
		pcs.firePropertyChange("procced", true, false);
	}    

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated Code">                          
	private void initComponents() {

		titleLabel = new javax.swing.JLabel();
		presentHighScorePanel = new javax.swing.JPanel();
		songLabel = new javax.swing.JLabel();
		artistLabel = new javax.swing.JLabel();
		congratsLabel = new javax.swing.JLabel();
		scoreLabel = new javax.swing.JLabel();
		proccedButton = new javax.swing.JButton();
		nameField = new JTextField[5];
		scoreField = new JTextField[5];
		for(int i = 0; i < 5; i++) {
			nameField[i] = new JTextField();
			scoreField[i] = new JTextField();
		}
		congratsLabel.setForeground(Color.white);
		titleLabel.setIcon(new javax.swing.ImageIcon("images\\score.png")); // NOI18N

		presentHighScorePanel.setBackground(new java.awt.Color(255, 255, 255));

		songLabel.setText("jLabel3");

		artistLabel.setText("jLabel4");

		congratsLabel.setText("You made the High-score list!");

		scoreLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		scoreLabel.setText("89000");

		javax.swing.GroupLayout presentHighScorePanelLayout = new javax.swing.GroupLayout(presentHighScorePanel);
		presentHighScorePanel.setLayout(presentHighScorePanelLayout);
		presentHighScorePanelLayout.setHorizontalGroup(
				presentHighScorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(presentHighScorePanelLayout.createSequentialGroup()
						.addGroup(presentHighScorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(presentHighScorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, presentHighScorePanelLayout.createSequentialGroup()
												.addComponent(nameField[4], javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
												.addComponent(scoreField[4], javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(presentHighScorePanelLayout.createSequentialGroup()
														.addGap(22, 22, 22)
														.addGroup(presentHighScorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																.addGroup(presentHighScorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																		.addGroup(presentHighScorePanelLayout.createSequentialGroup()
																				.addComponent(nameField[1], javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
																				.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
																				.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, presentHighScorePanelLayout.createSequentialGroup()
																						.addComponent(nameField[2], javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addGap(10, 10, 10)))
																						.addGroup(presentHighScorePanelLayout.createSequentialGroup()
																								.addGroup(presentHighScorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																										.addComponent(nameField[0], javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addComponent(artistLabel)
																										.addComponent(songLabel))
																										.addGap(10, 10, 10)))
																										.addGroup(presentHighScorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
																												.addComponent(scoreField[0], javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
																												.addComponent(scoreField[1], javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
																												.addComponent(scoreField[2], javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
																												.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, presentHighScorePanelLayout.createSequentialGroup()
																														.addComponent(nameField[3], javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
																														.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																														.addComponent(scoreField[3], javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
																														.addGroup(presentHighScorePanelLayout.createSequentialGroup()
																																.addGap(71, 71, 71)
																																.addGroup(presentHighScorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
																																		.addComponent(scoreLabel)
																																		.addComponent(congratsLabel))))
																																		.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				);
		presentHighScorePanelLayout.setVerticalGroup(
				presentHighScorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(presentHighScorePanelLayout.createSequentialGroup()
						.addContainerGap()
						.addComponent(congratsLabel)
						.addGap(29, 29, 29)
						.addGroup(presentHighScorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(songLabel)
								.addComponent(scoreLabel))
								.addGap(18, 18, 18)
								.addComponent(artistLabel)
								.addGap(18, 18, 18)
								.addGroup(presentHighScorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(nameField[0], javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(scoreField[0], javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(18, 18, 18)
										.addGroup(presentHighScorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(nameField[1], javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(scoreField[1], javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGap(18, 18, 18)
												.addGroup(presentHighScorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(nameField[2], javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(scoreField[2], javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGap(18, 18, 18)
														.addGroup(presentHighScorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																.addComponent(nameField[3], javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
																.addComponent(scoreField[3], javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
																.addGap(18, 18, 18)
																.addGroup(presentHighScorePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
																		.addComponent(nameField[4], javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(scoreField[4], javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addContainerGap(23, Short.MAX_VALUE))
				);

		proccedButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("images\\back.png"))); // NOI18N
		proccedButton.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				proccedButtonActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addGap(326, 326, 326)
						.addComponent(titleLabel)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
								.addGap(29, 311, Short.MAX_VALUE)
								.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
										.addComponent(proccedButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(presentHighScorePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
										.addGap(311, 311, 311))
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addGap(35, 35, 35)
						.addComponent(titleLabel)
						.addGap(28, 28, 28)
						.addComponent(presentHighScorePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addComponent(proccedButton)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				);
	}                                       
	// Variables declaration - do not modify                     
	private javax.swing.JLabel artistLabel;
	private javax.swing.JLabel congratsLabel;
	private javax.swing.JPanel presentHighScorePanel;
	private javax.swing.JButton proccedButton;
	private javax.swing.JLabel scoreLabel;
	private javax.swing.JLabel songLabel;
	private javax.swing.JLabel titleLabel;
	private JTextField[] nameField;
	private JTextField[] scoreField;
	public PropertyChangeSupport pcs;


	// End of variables declaration                   
}