package gui;

import java.awt.Graphics;
import java.util.List;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;

import javax.imageio.ImageIO;

import musichandler.Song;

/**
*
* @author Björn Hedström
*/
public class SongSelection extends javax.swing.JPanel {
	
   /**
    * Creates new form SongSelection
    */
   public SongSelection(List<Song> songList) {
	   this.songList = songList;
       initComponents();
       repaint();
   } 
   
   public void paintComponent(Graphics g) {
	   
	   BufferedImage image = null;
	   try {
		   image = ImageIO.read(new File("C:\\Users\\edge\\Downloads\\speaker.png"));
	   } catch (IOException e) {
		   e.printStackTrace();
	   }
	   g.drawImage(image, 0, 0, null);
   }
   
   public void presentSongList(int newFirst) {
	   
	   if(newFirst > 0 ) {
		   previousButton.setVisible(true);
	   }
		
	   for(int i = 0; i < 4; i++) {
		   if(songList.get(newFirst + i) != null) {
			   (songPanels[0].getSongNameLabel()).setText(songList.get(newFirst + i).getSongName());
			   (songPanels[0].getArtistLabel()).setText(songList.get(newFirst + i).getArtist());
			   (songPanels[0].getGenreLabel()).setText(songList.get(newFirst + i).getGenre());
		   }
	   }	   
   }
   
   //autogenerated code starts here

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   private void initComponents() {
	   
	   titleLabel = new javax.swing.JLabel();
	   /*
       songPanels[0] = new SongPanel();
       songPanels[1] = new SongPanel();
       songPanels[2] = new SongPanel();
       songPanels[3] = new SongPanel();
       */
       nextButton = new javax.swing.JButton();
       previousButton = new javax.swing.JButton();
       backButton = new javax.swing.JButton();
       searchField = new javax.swing.JTextField();
       searchButton = new javax.swing.JButton();
       songPanels = new SongPanel[3];
       
       previousButton.setVisible(false);
       setBackground(new java.awt.Color(255, 255, 255));

       titleLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\edge\\Downloads\\chooseASong.png")); // NOI18N

       nextButton.setText("Next");

       previousButton.setText("Previous");
       
       backButton.setBackground(new java.awt.Color(204, 204, 204));
       backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("images\\back.png"))); // NOI18N
       backButton.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               backButtonActionPerformed(evt);
           }
       });

       searchField.setSelectionColor(new java.awt.Color(102, 102, 102));

       searchButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\edge\\Pictures\\search.png")); // NOI18N

       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
       this.setLayout(layout);
       layout.setHorizontalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addContainerGap(153, Short.MAX_VALUE)
               .addComponent(titleLabel)
               .addGap(153, 153, 153))
           .addGroup(layout.createSequentialGroup()
               .addGap(332, 332, 332)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                   .addGroup(layout.createSequentialGroup()
                       .addComponent(previousButton)
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                       .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                   .addComponent(songPanels[3], javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                   .addComponent(songPanels[2], javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                   .addComponent(songPanels[1], javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                   .addComponent(songPanels[0], javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                   .addComponent(backButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                   .addGroup(layout.createSequentialGroup()
                       .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                       .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
       );
       layout.setVerticalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addGap(35, 35, 35)
               .addComponent(titleLabel)
               .addGap(26, 26, 26)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addComponent(songPanels[0], javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addComponent(songPanels[1], javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addComponent(songPanels[2], javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addComponent(songPanels[3], javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(previousButton)
                   .addComponent(nextButton))
               .addGap(26, 26, 26)
               .addComponent(backButton)
               .addContainerGap(48, Short.MAX_VALUE))
       );
   }// </editor-fold>                        

   private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {  
	   ((CardPanel)this.getParent()).back();
   }                                          


   // Variables declaration - do not modify     
   private SongPanel[] songPanels;
   private javax.swing.JButton backButton;
   private javax.swing.JButton nextButton;
   private javax.swing.JButton previousButton;
   private javax.swing.JButton searchButton;
   private javax.swing.JTextField searchField;
   /*
   private SongPanel songPanels[0];
   private SongPanel songPanels[1];
   private SongPanel songPanels[2];
   private SongPanel songPanels[3];
   */
   private javax.swing.JLabel titleLabel;
   private List<Song> songList;
   // End of variables declaration                   
}