package gui;

import java.awt.CardLayout;
import java.awt.Graphics;
import java.awt.List;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;

import javax.imageio.ImageIO;

import musichandler.Song;

/**
*
* @author Björn Hedström
*/
public class SongSelection extends javax.swing.JPanel {

   /**
    * Creates new form SongSelection
    */
   public SongSelection() {
       initComponents();
       repaint();
   } 
   
   public void paintComponent(Graphics g) {
	   
		BufferedImage image = null;
		try {
			image = ImageIO.read(new File("C:\\Users\\edge\\Downloads\\speaker.png"));
		} catch (IOException e) {
			e.printStackTrace();
		}
		   g.drawImage(image, 0, 0, null);
   }
   
   //autogenerated code starts here

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   private void initComponents() {

       titleLabel = new javax.swing.JLabel();
       songPanel1 = new SongPanel();
       songPanel2 = new SongPanel();
       songPanel3 = new SongPanel();
       songPanel4 = new SongPanel();
       nextButton = new javax.swing.JButton();
       previousButton = new javax.swing.JButton();
       backButton = new javax.swing.JButton();
       searchField = new javax.swing.JTextField();
       searchButton = new javax.swing.JButton();

       setBackground(new java.awt.Color(255, 255, 255));

       titleLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\edge\\Downloads\\chooseASong.png")); // NOI18N

       nextButton.setText("Next");

       previousButton.setText("Previous");
       
       backButton.setBackground(new java.awt.Color(204, 204, 204));
       backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("images\\back.png"))); // NOI18N
       backButton.addActionListener(new java.awt.event.ActionListener() {
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               backButtonActionPerformed(evt);
           }
       });

       searchField.setSelectionColor(new java.awt.Color(102, 102, 102));

       searchButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\edge\\Pictures\\search.png")); // NOI18N

       javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
       this.setLayout(layout);
       layout.setHorizontalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addContainerGap(153, Short.MAX_VALUE)
               .addComponent(titleLabel)
               .addGap(153, 153, 153))
           .addGroup(layout.createSequentialGroup()
               .addGap(332, 332, 332)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                   .addGroup(layout.createSequentialGroup()
                       .addComponent(previousButton)
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                       .addComponent(nextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                   .addComponent(songPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                   .addComponent(songPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                   .addComponent(songPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                   .addComponent(songPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                   .addComponent(backButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                   .addGroup(layout.createSequentialGroup()
                       .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                       .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                       .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
               .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
       );
       layout.setVerticalGroup(
           layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
           .addGroup(layout.createSequentialGroup()
               .addGap(35, 35, 35)
               .addComponent(titleLabel)
               .addGap(26, 26, 26)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                   .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addComponent(songPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addComponent(songPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addComponent(songPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addComponent(songPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                   .addComponent(previousButton)
                   .addComponent(nextButton))
               .addGap(26, 26, 26)
               .addComponent(backButton)
               .addContainerGap(48, Short.MAX_VALUE))
       );
   }// </editor-fold>                        

   private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {  
	   ((CardPanel)this.getParent()).back();
   }                                          


   // Variables declaration - do not modify                     
   private javax.swing.JButton backButton;
   private javax.swing.JButton nextButton;
   private javax.swing.JButton previousButton;
   private javax.swing.JButton searchButton;
   private javax.swing.JTextField searchField;
   private SongPanel songPanel1;
   private SongPanel songPanel2;
   private SongPanel songPanel3;
   private SongPanel songPanel4;
   private javax.swing.JLabel titleLabel;
   // End of variables declaration                   
}